name: Deploy to Cloud Run

on:
  push:
    branches: [ Frist_Brench ]
  workflow_dispatch:

env:
  PROJECT_ID: bamboo-strata-274419
  SERVICE: testflaskserver2
  REGION: us-central1
  REGISTRY: gcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker for GCR
      run: |
        echo "🔧 Configuring Docker for Google Container Registry..."
        gcloud auth configure-docker --quiet

    - name: Build and Push Container Image
      run: |
        echo "🔨 Building container image..."
        IMAGE_URI="${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
        
        # Build the Docker image
        docker build -t $IMAGE_URI .
        
        echo "📤 Pushing image to Google Container Registry..."
        docker push $IMAGE_URI
        
        echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV

    - name: Deploy to Cloud Run
      run: |
        echo "🚀 Deploying to Cloud Run..."
        
        # Deploy from pre-built image (no Cloud Build needed)
        gcloud run deploy ${{ env.SERVICE }} \
          --image ${{ env.IMAGE_URI }} \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --port 8080 \
          --memory 1Gi \
          --cpu 1 \
          --max-instances 10 \
          --timeout 300s \
          --project ${{ env.PROJECT_ID }} \
          --execution-environment gen2 \
          --quiet

    - name: Get Service URL and Test
      run: |
        echo "🌐 Getting service URL..."
        SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE }} --region=${{ env.REGION }} --project=${{ env.PROJECT_ID }} --format='value(status.url)')
        
        if [ -z "$SERVICE_URL" ]; then
          echo "❌ Failed to get service URL"
          exit 1
        fi
        
        echo "✅ Service deployed successfully!"
        echo "🌐 Main URL: $SERVICE_URL"
        echo "♟️  Chess Game: $SERVICE_URL/chess"
        echo "🔍 Health Check: $SERVICE_URL/api/health"
        
        # Test the deployment
        echo "🧪 Testing deployment..."
        if curl -f -s "$SERVICE_URL/api/health" > /dev/null; then
          echo "✅ Health check passed!"
          echo "::notice title=Deployment Success::Chess game deployed successfully to $SERVICE_URL/chess"
        else
          echo "⚠️  Health check failed, but service is deployed"
          echo "::warning title=Health Check::Service deployed but health check failed"
        fi