name: Deploy to Cloud Run

on:
  push:
    branches: [ Frist_Brench ]
  workflow_dispatch:

env:
  PROJECT_ID: bamboo-strata-274419
  SERVICE: testflaskserver2
  REGION: us-central1

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
        project_id: ${{ env.PROJECT_ID }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Verify Authentication
      run: |
        gcloud auth list
        gcloud config list
        echo "Project: ${{ env.PROJECT_ID }}"
        echo "Service: ${{ env.SERVICE }}"
        echo "Region: ${{ env.REGION }}"

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.SERVICE }} \
          --source . \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --port 8000 \
          --memory 1Gi \
          --cpu 1 \
          --max-instances 10 \
          --timeout 300s \
          --project ${{ env.PROJECT_ID }}

    - name: Get Service URL
      run: |
        SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE }} --region=${{ env.REGION }} --project=${{ env.PROJECT_ID }} --format='value(status.url)')
        echo "✅ Service deployed successfully!"
        echo "🌐 Main URL: $SERVICE_URL"
        echo "♟️  Chess Game: $SERVICE_URL/chess"
        echo "::notice title=Deployment Success::Chess game deployed to $SERVICE_URL/chess"